version: 2
jobs:
  core:
    machine: true
    parallelism: 4
    working_directory: ~/gravityflow
    steps:
      - checkout
      - run:
          name: Split the tests
          command: |
            mkdir ~/gravityflow/tests/acceptance-tests/acceptance/ci-split-tests
            TESTFILES=$(circleci tests glob ~/gravityflow/tests/acceptance-tests/acceptance/[^_]*.php | circleci tests split --split-by=timings)
            echo ${TESTFILES} | xargs -n 1 echo
            cp ${TESTFILES} ~/gravityflow/tests/acceptance-tests/acceptance/ci-split-tests
      - run:
          name: Run acceptance tests
          command: |
            docker-compose run --rm codeception run --html --xml -vvv -o "groups: ci-split-tests: [tests/acceptance-tests/acceptance/ci-split-tests]" -g ci-split-tests
      - store_artifacts:
          path: ~/gravityflow/tests/acceptance-tests/_output
      - store_test_results:
          path: ~/gravityflow/tests/acceptance-tests/_output

  form_connector:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Trigger the Build Job for the Form Connnector Extension
          command: |
            printf "Triggering the Build Job for the Form Connnector Extension\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/gravityflow/gravityflowformconnector/tree/master?circle-token=$CIRCLE_TOKEN")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/gravityflow/gravityflowformconnector/tree/master"

  incoming_webhook:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Trigger the Build Job for the Incoming Webhook Extension
          command: |
            printf "Triggering the Build Job for the Incoming Webhook Extension\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/gravityflow/gravityflowincomingwebhook/tree/master?circle-token=$CIRCLE_TOKEN")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/gravityflow/gravityflowincomingwebhook/tree/master"

workflows:
  version: 2
  core_plus_extensions:
    jobs:
      - core
      - form_connector:
          requires:
            - core
      - incoming_webhook:
          requires:
            - core